### ISSUE TITLE
feat: update licensing API to reduce number rest api query and handle existing types of licenses with All access passes

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give-edd-software-licensing-api#1]
## Description
Purpose of this issue to discuss a possible solution to reducing the number of restAPI call for EDD.

Currently, each site does separate API call for each add-on.

We get API calls for:
1. license check 
2. get version ( done by EDD auto update )
3. refresh license (as per my idea)
     this will allow the user to manually refresh the license instead of waiting for a weekly cron job.
4. Activate add-on
5. deactivate the add-on
6 subscription check

## Possible Solution
we can reduce the number of API calls by merging them into one API query.
For example:
1. only weekly bulk license check + get the version
3. refresh license ( allow on two requests per day after that it will lock itself). WordPress also provides `Check Now` button under `Dashboard > Updates`

By this way, we will get only on API call weekly from any website and three on a rare day when user will use a manual refresh functionality.

**Comment by ravinderk** [comment]
Slack Chat Summary

Participants: @DevinWalker, @ravinderk 
Topic: Discussion about this issue
Result:
- [x] Implement bulk check logic of licenses
- [x] Setup monthly bulk license check
- [x] Setup button to refresh bulk licenses ( 5 times per day )
- [x] <s>Deactivate license when rest API when getting a query from unregistered site</s>: deactivation will be a not correct way because we can not deactivate the license for unregister site. another way to prevent unauthorized addon update request by add check on `get_version` rest request, so if license activates for the particular site then the response will contain addon information otherwise error msg.
```
{
    "new_version": "",
    "stable_version": "",
    "sections": "",
    "license_check": "",
    "msg": "Site not active"
}
```

**Comment by DevinWalker** [comment]
Resolved via https://github.com/impress-org/give-edd-software-licensing-api/pull/2
